externalURL: https://core.harbor.domain
persistence:
  persistentVolumeClaim:
    registry:
      storageClass: alicloud-disk-topology-alltype
      size: 40Gi
    database:
      storageClass: alicloud-disk-topology-alltype
      size: 40Gi
    jobservice:
      jobLog:
        storageClass: alicloud-disk-topology-alltype
        size: 40Gi
    trivy:
      storageClass: alicloud-disk-topology-alltype
      size: 40Gi
    redis:
      storageClass: alicloud-disk-topology-alltype
      size: 40Gi
  enabled: true
harborAdminPassword: Harbor12345
expose:
  tls:
    auto:
      commonName: core.harbor.domain
  type: loadBalancer
