image-mapping:
- goharbor/trivy-adapter-photon:v2.12.1: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/goharbor/trivy-adapter-photon:v2.12.1
- goharbor/harbor-jobservice:v2.12.1: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/goharbor/harbor-jobservice:v2.12.1
- goharbor/harbor-registryctl:v2.12.1: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/goharbor/harbor-registryctl:v2.12.1
- goharbor/harbor-portal:v2.12.1: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/goharbor/harbor-portal:v2.12.1
- goharbor/redis-photon:v2.12.1: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/goharbor/redis-photon:v2.12.1
- goharbor/registry-photon:v2.12.1: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/goharbor/registry-photon:v2.12.1
- goharbor/nginx-photon:v2.12.1: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/goharbor/nginx-photon:v2.12.1
- goharbor/harbor-db:v2.12.1: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/goharbor/harbor-db:v2.12.1
- goharbor/harbor-core:v2.12.1: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/goharbor/harbor-core:v2.12.1
